config/routes.rb
Rails.application.routes.draw do
  resources :inventarios
  resources :organizacion_beneficas
  resources :cuenta_bancaria
  resources :establecimientos
  resources :responsables
  resources :donacions
  resources :almacens
  resources :solicituds
  resources :economicas
  resources :alimentos
  resources :productos
  resources :voluntarios
  resources :personas
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/models/alimento.rb
class Alimento < ApplicationRecord
end

app/models/almacen.rb
class Almacen < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cuenta_bancarium.rb
class CuentaBancarium < ApplicationRecord
end

app/models/donacion.rb
class Donacion < ApplicationRecord
  belongs_to :producto
  belongs_to :alimento
  belongs_to :solicitud
end

app/models/economica.rb
class Economica < ApplicationRecord
end

app/models/establecimiento.rb
class Establecimiento < ApplicationRecord
end

app/models/inventario.rb
class Inventario < ApplicationRecord
end

app/models/persona.rb
class Persona < ApplicationRecord
end

app/models/producto.rb
class Producto < ApplicationRecord
end

app/models/responsable.rb
class Responsable < ApplicationRecord
end

app/models/solicitud.rb
class Solicitud < ApplicationRecord
  belongs_to :voluntario
  belongs_to :organizacion_benefica
  belongs_to :inventario
  belongs_to :user
end

app/models/voluntario.rb
class Voluntario < ApplicationRecord
  belongs_to :persona
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end

end

app/helpers/alimentos_helper.rb
module AlimentosHelper
end

app/helpers/almacens_helper.rb
module AlmacensHelper
end

app/helpers/donacions_helper.rb
module DonacionsHelper
end

app/helpers/economicas_helper.rb
module EconomicasHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/personas_helper.rb
module PersonasHelper
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/helpers/solicituds_helper.rb
module SolicitudsHelper
end

app/views/home/index.html.erb
<div class="flex flex-col gap-4">
  <%= link_to "Persona", personas_path, html_options ={class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"} %>
  <%= link_to "Voluntarios", voluntarios_path, html_options ={class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"} %>
  <%= link_to "Productos", productos_path, html_options ={class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"} %>
  <%= link_to "Alimentos", alimentos_path, html_options ={class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"} %>
  <%= link_to "Economica", economicas_path, html_options ={class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"} %>
  <%= link_to "Organizacion Benefica", organizacion_beneficas_path, html_options ={class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"} %>
  <%= link_to "Solicitud", solicituds_path, html_options ={class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"} %>
  <%= link_to "Almacen", almacens_path, html_options ={class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"} %>
  <%= link_to "Inventario", inventarios_path, html_options ={class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"} %>
  <%= link_to "Donacion", donacions_path, html_options ={class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"} %>
  <%= link_to "Responsable", responsables_path, html_options ={class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"} %>
  <%= link_to "Establecimiento", establecimientos_path, html_options ={class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"} %>
  <%= link_to "Cuenta Bancaria", cuenta_bancaria_path, html_options ={class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"} %>
  
</div>