config/routes.rb
Rails.application.routes.draw do
  resources :inventarios
  resources :organizacion_beneficas
  resources :cuenta_bancaria
  resources :establecimientos
  resources :responsables
  resources :donacions
  resources :almacens
  resources :solicituds
  resources :economicas
  resources :alimentos
  resources :productos
  resources :voluntarios
  resources :personas
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/models/alimento.rb
class Alimento < ApplicationRecord
end

app/models/almacen.rb
class Almacen < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cuenta_bancarium.rb
class CuentaBancarium < ApplicationRecord
end

app/models/donacion.rb
class Donacion < ApplicationRecord
  belongs_to :producto
  belongs_to :alimento
  belongs_to :solicitud
end

app/models/economica.rb
class Economica < ApplicationRecord
end

app/models/establecimiento.rb
class Establecimiento < ApplicationRecord
end

app/models/inventario.rb
class Inventario < ApplicationRecord
end

app/models/persona.rb
class Persona < ApplicationRecord
end

app/models/producto.rb
class Producto < ApplicationRecord
end

app/models/responsable.rb
class Responsable < ApplicationRecord
end

app/models/solicitud.rb
class Solicitud < ApplicationRecord
  belongs_to :voluntario
  belongs_to :organizacion_benefica
  belongs_to :inventario
  belongs_to :user
end

app/models/voluntario.rb
class Voluntario < ApplicationRecord
  belongs_to :persona
end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  before_action :set_producto, only: %i[ show edit update destroy ]

  # GET /productos or /productos.json
  def index
    @productos = Producto.all
  end

  # GET /productos/1 or /productos/1.json
  def show
  end

  # GET /productos/new
  def new
    @producto = Producto.new
  end

  # GET /productos/1/edit
  def edit
  end

  # POST /productos or /productos.json
  def create
    @producto = Producto.new(producto_params)

    respond_to do |format|
      if @producto.save
        format.html { redirect_to producto_url(@producto), notice: "Producto was successfully created." }
        format.json { render :show, status: :created, location: @producto }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /productos/1 or /productos/1.json
  def update
    respond_to do |format|
      if @producto.update(producto_params)
        format.html { redirect_to producto_url(@producto), notice: "Producto was successfully updated." }
        format.json { render :show, status: :ok, location: @producto }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productos/1 or /productos/1.json
  def destroy
    @producto.destroy

    respond_to do |format|
      format.html { redirect_to productos_url, notice: "Producto was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_producto
      @producto = Producto.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def producto_params
      params.require(:producto).permit(:name, :description, :quantity)
    end
end

app/helpers/alimentos_helper.rb
module AlimentosHelper
end

app/helpers/almacens_helper.rb
module AlmacensHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/donacions_helper.rb
module DonacionsHelper
end

app/helpers/economicas_helper.rb
module EconomicasHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/personas_helper.rb
module PersonasHelper
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/helpers/solicituds_helper.rb
module SolicitudsHelper
end

app/views/productos/_form.html.erb
<%= form_with(model: producto, class: "contents") do |form| %>
  <% if producto.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(producto.errors.count, "error") %> prohibited this producto from being saved:</h2>

      <ul>
        <% producto.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :quantity %>
    <%= form.number_field :quantity, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/productos/_producto.html.erb
<div id="<%= dom_id producto %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= producto.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= producto.description %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Quantity:</strong>
    <%= producto.quantity %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this producto", producto, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this producto", edit_producto_path(producto), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/productos/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing producto</h1>

  <%= render "form", producto: @producto %>

  <%= link_to "Show this producto", @producto, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to productos", productos_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/productos/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Productos</h1>
    <%= link_to "New producto", new_producto_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="productos" class="min-w-full">
    <%= render @productos %>
  </div>
</div>

app/views/productos/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New producto</h1>

  <%= render "form", producto: @producto %>

  <%= link_to "Back to productos", productos_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/productos/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @producto %>

    <%= link_to "Edit this producto", edit_producto_path(@producto), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this producto", producto_path(@producto), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to productos", productos_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>