config/routes.rb
Rails.application.routes.draw do
  resources :inventarios
  resources :organizacion_beneficas
  resources :cuenta_bancaria
  resources :establecimientos
  resources :responsables
  resources :donacions
  resources :almacens
  resources :solicituds
  resources :economicas
  resources :alimentos
  resources :productos
  resources :voluntarios
  resources :personas
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/models/alimento.rb
class Alimento < ApplicationRecord
end

app/models/almacen.rb
class Almacen < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cuenta_bancarium.rb
class CuentaBancarium < ApplicationRecord
end

app/models/donacion.rb
class Donacion < ApplicationRecord
  belongs_to :producto
  belongs_to :alimento
  belongs_to :solicitud
end

app/models/economica.rb
class Economica < ApplicationRecord
end

app/models/establecimiento.rb
class Establecimiento < ApplicationRecord
end

app/models/inventario.rb
class Inventario < ApplicationRecord
end

app/models/persona.rb
class Persona < ApplicationRecord
end

app/models/producto.rb
class Producto < ApplicationRecord
end

app/models/responsable.rb
class Responsable < ApplicationRecord
end

app/models/solicitud.rb
class Solicitud < ApplicationRecord
  belongs_to :voluntario
  belongs_to :organizacion_benefica
  belongs_to :inventario
  belongs_to :user
end

app/models/voluntario.rb
class Voluntario < ApplicationRecord
  belongs_to :persona
end

app/controllers/alimentos_controller.rb
class AlimentosController < ApplicationController
  before_action :set_alimento, only: %i[ show edit update destroy ]

  # GET /alimentos or /alimentos.json
  def index
    @alimentos = Alimento.all
  end

  # GET /alimentos/1 or /alimentos/1.json
  def show
  end

  # GET /alimentos/new
  def new
    @alimento = Alimento.new
  end

  # GET /alimentos/1/edit
  def edit
  end

  # POST /alimentos or /alimentos.json
  def create
    @alimento = Alimento.new(alimento_params)

    respond_to do |format|
      if @alimento.save
        format.html { redirect_to alimento_url(@alimento), notice: "Alimento was successfully created." }
        format.json { render :show, status: :created, location: @alimento }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @alimento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alimentos/1 or /alimentos/1.json
  def update
    respond_to do |format|
      if @alimento.update(alimento_params)
        format.html { redirect_to alimento_url(@alimento), notice: "Alimento was successfully updated." }
        format.json { render :show, status: :ok, location: @alimento }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @alimento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alimentos/1 or /alimentos/1.json
  def destroy
    @alimento.destroy

    respond_to do |format|
      format.html { redirect_to alimentos_url, notice: "Alimento was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alimento
      @alimento = Alimento.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def alimento_params
      params.require(:alimento).permit(:name, :description, :quantity)
    end
end

app/helpers/alimentos_helper.rb
module AlimentosHelper
end

app/helpers/almacens_helper.rb
module AlmacensHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/donacions_helper.rb
module DonacionsHelper
end

app/helpers/economicas_helper.rb
module EconomicasHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/personas_helper.rb
module PersonasHelper
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/helpers/solicituds_helper.rb
module SolicitudsHelper
end

app/views/alimentos/_alimento.html.erb
<div id="<%= dom_id alimento %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= alimento.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= alimento.description %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Quantity:</strong>
    <%= alimento.quantity %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this alimento", alimento, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this alimento", edit_alimento_path(alimento), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/alimentos/_form.html.erb
<%= form_with(model: alimento, class: "contents") do |form| %>
  <% if alimento.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(alimento.errors.count, "error") %> prohibited this alimento from being saved:</h2>

      <ul>
        <% alimento.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :quantity %>
    <%= form.number_field :quantity, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/alimentos/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing alimento</h1>

  <%= render "form", alimento: @alimento %>

  <%= link_to "Show this alimento", @alimento, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to alimentos", alimentos_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/alimentos/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Alimentos</h1>
    <%= link_to "New alimento", new_alimento_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="alimentos" class="min-w-full">
    <%= render @alimentos %>
  </div>
</div>

app/views/alimentos/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New alimento</h1>

  <%= render "form", alimento: @alimento %>

  <%= link_to "Back to alimentos", alimentos_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/alimentos/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @alimento %>

    <%= link_to "Edit this alimento", edit_alimento_path(@alimento), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this alimento", alimento_path(@alimento), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to alimentos", alimentos_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>