config/routes.rb
Rails.application.routes.draw do
  resources :inventarios
  resources :organizacion_beneficas
  resources :cuenta_bancaria
  resources :establecimientos
  resources :responsables
  resources :donacions
  resources :almacens
  resources :solicituds
  resources :economicas
  resources :alimentos
  resources :productos
  resources :voluntarios
  resources :personas
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/models/alimento.rb
class Alimento < ApplicationRecord
end

app/models/almacen.rb
class Almacen < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cuenta_bancarium.rb
class CuentaBancarium < ApplicationRecord
end

app/models/donacion.rb
class Donacion < ApplicationRecord
  belongs_to :producto
  belongs_to :alimento
  belongs_to :solicitud
end

app/models/economica.rb
class Economica < ApplicationRecord
end

app/models/establecimiento.rb
class Establecimiento < ApplicationRecord
end

app/models/inventario.rb
class Inventario < ApplicationRecord
end

app/models/persona.rb
class Persona < ApplicationRecord
end

app/models/producto.rb
class Producto < ApplicationRecord
end

app/models/responsable.rb
class Responsable < ApplicationRecord
end

app/models/solicitud.rb
class Solicitud < ApplicationRecord
  belongs_to :voluntario
  belongs_to :organizacion_benefica
  belongs_to :inventario
  belongs_to :user
end

app/models/voluntario.rb
class Voluntario < ApplicationRecord
  belongs_to :persona
end

app/controllers/almacens_controller.rb
class AlmacensController < ApplicationController
  before_action :set_almacen, only: %i[ show edit update destroy ]

  # GET /almacens or /almacens.json
  def index
    @almacens = Almacen.all
  end

  # GET /almacens/1 or /almacens/1.json
  def show
  end

  # GET /almacens/new
  def new
    @almacen = Almacen.new
  end

  # GET /almacens/1/edit
  def edit
  end

  # POST /almacens or /almacens.json
  def create
    @almacen = Almacen.new(almacen_params)

    respond_to do |format|
      if @almacen.save
        format.html { redirect_to almacen_url(@almacen), notice: "Almacen was successfully created." }
        format.json { render :show, status: :created, location: @almacen }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @almacen.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /almacens/1 or /almacens/1.json
  def update
    respond_to do |format|
      if @almacen.update(almacen_params)
        format.html { redirect_to almacen_url(@almacen), notice: "Almacen was successfully updated." }
        format.json { render :show, status: :ok, location: @almacen }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @almacen.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /almacens/1 or /almacens/1.json
  def destroy
    @almacen.destroy

    respond_to do |format|
      format.html { redirect_to almacens_url, notice: "Almacen was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_almacen
      @almacen = Almacen.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def almacen_params
      params.require(:almacen).permit(:name, :description, :location)
    end
end

app/helpers/alimentos_helper.rb
module AlimentosHelper
end

app/helpers/almacens_helper.rb
module AlmacensHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/donacions_helper.rb
module DonacionsHelper
end

app/helpers/economicas_helper.rb
module EconomicasHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/personas_helper.rb
module PersonasHelper
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/helpers/solicituds_helper.rb
module SolicitudsHelper
end

app/views/almacens/_almacen.html.erb
<div id="<%= dom_id almacen %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= almacen.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= almacen.description %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Location:</strong>
    <%= almacen.location %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this almacen", almacen, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this almacen", edit_almacen_path(almacen), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/almacens/_form.html.erb
<%= form_with(model: almacen, class: "contents") do |form| %>
  <% if almacen.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(almacen.errors.count, "error") %> prohibited this almacen from being saved:</h2>

      <ul>
        <% almacen.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :location %>
    <%= form.text_field :location, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/almacens/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing almacen</h1>

  <%= render "form", almacen: @almacen %>

  <%= link_to "Show this almacen", @almacen, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to almacens", almacens_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/almacens/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Almacens</h1>
    <%= link_to "New almacen", new_almacen_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="almacens" class="min-w-full">
    <%= render @almacens %>
  </div>
</div>

app/views/almacens/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New almacen</h1>

  <%= render "form", almacen: @almacen %>

  <%= link_to "Back to almacens", almacens_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/almacens/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @almacen %>

    <%= link_to "Edit this almacen", edit_almacen_path(@almacen), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this almacen", almacen_path(@almacen), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to almacens", almacens_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>